import { Category, EventData, Feedback } from "../types";

export const CATEGORIES: Category[] = [
  {
    id: "art",
    label: "Art Workshop",
    emoji: "🎨",
    color: "#C84B31",
    bgColor: "#FEF2EE",
  },
  {
    id: "dance",
    label: "Dance",
    emoji: "💃",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
  },
  {
    id: "food",
    label: "Food Festival",
    emoji: "🍜",
    color: "#D97706",
    bgColor: "#FFFBEB",
  },
  {
    id: "mudpot",
    label: "Mud Pot",
    emoji: "🏺",
    color: "#92400E",
    bgColor: "#FEF3C7",
  },
  {
    id: "tech",
    label: "Tech Meetup",
    emoji: "💻",
    color: "#1D4ED8",
    bgColor: "#EFF6FF",
  },
  {
    id: "strangers",
    label: "Strangers Meetup",
    emoji: "🤝",
    color: "#059669",
    bgColor: "#ECFDF5",
  },
  {
    id: "cinema",
    label: "Cinema",
    emoji: "🎬",
    color: "#E11D48",
    bgColor: "#FFF1F2",
  },
  {
    id: "comedy",
    label: "Standup Comedy",
    emoji: "🎤",
    color: "#7E22CE",
    bgColor: "#FAF5FF",
  },
];

export const ALL_EVENTS: EventData[] = [
  {
    id: "art-1",
    categoryId: "art",
    title: "Watercolor Horizon Workshop",
    description:
      "Paint breathtaking sunsets using professional watercolor techniques guided by an award-winning artist.",
    fullDescription:
      "Join Priya Menon for an immersive 3-hour watercolor journey. You'll learn wet-on-wet techniques, color blending, and horizon composition. All materials provided — just bring your curiosity. Refreshments included.",
    ticketTiers: [
      {
        id: "a1-eb",
        name: "Early Bird Artist",
        price: 199,
        totalSeats: 10,
        bookedSeats: 8,
        heldSeats: 0,
      },
      {
        id: "a1-reg",
        name: "Regular Admission",
        price: 349,
        totalSeats: 20,
        bookedSeats: 10,
        heldSeats: 0,
      },
    ],
    location: "Studio 14, Koramangala, Bengaluru",
    hostedBy: "Priya Menon (MFA, Mysore School of Art)",
    duration: "3 hours",
    date: "Aug 10, 2026 · 10:00 AM",
    ageCategory: "16+",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=700",
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=700",
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=700",
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=700",
    ],
    price: "From ₹199",
    tags: ["Painting", "Beginner Friendly", "Materials Included"],
  },
  {
    id: "art-2",
    categoryId: "art",
    title: "Pottery & Soul",
    description:
      "Wheel-throwing and hand-building pottery with a master craftsman. Take home your creation.",
    fullDescription:
      "Ramesh Kumar, with 20+ years on the wheel, guides you through centering clay, pulling walls, and natural drying. You take home your fired, glazed creation wrapped and ready.",
    ticketTiers: [
      {
        id: "a2-eb",
        name: "Early Potter",
        price: 299,
        totalSeats: 10,
        bookedSeats: 10,
        heldSeats: 0,
      },
      {
        id: "a2-reg",
        name: "Standard Slot",
        price: 499,
        totalSeats: 10,
        bookedSeats: 5,
        heldSeats: 0,
      },
    ],
    location: "Clay Corner Studio, Indiranagar, Bengaluru",
    hostedBy: "Ramesh Kumar, Master Potter",
    duration: "4 hours",
    date: "Aug 17, 2026 · 11:00 AM",
    ageCategory: "14+",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=700",
    images: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=700",
      "https://images.unsplash.com/photo-1593150501174-d88aa1b7bb67?w=700",
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=700",
    ],
    price: "From ₹299",
    tags: ["Pottery", "Hands-on", "Take Home Piece"],
  },
  {
    id: "dance-1",
    categoryId: "dance",
    title: "Salsa Night Fever",
    description:
      "Latin dance social with a beginner mini-class, live DJ, and vibrant energy for all levels.",
    fullDescription:
      "Whether you have two left feet or Latin fire in your hips, Salsa Night Fever welcomes you. Marco & Sunita Dance Co. kick off with a 45-min fundamentals class.",
    ticketTiers: [
      {
        id: "d1-eb",
        name: "Early Salsa Pass",
        price: 150,
        totalSeats: 30,
        bookedSeats: 20,
        heldSeats: 0,
      },
      {
        id: "d1-reg",
        name: "General Admission",
        price: 300,
        totalSeats: 50,
        bookedSeats: 25,
        heldSeats: 0,
      },
    ],
    location: "The Dance Loft, HSR Layout, Bengaluru",
    hostedBy: "Marco & Sunita Dance Co.",
    duration: "3 hours",
    date: "Aug 9, 2026 · 7:00 PM",
    ageCategory: "18+",
    image: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=700",
    images: [
      "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=700",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=700",
      "https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=700",
    ],
    price: "From ₹150",
    tags: ["Latin Dance", "All Levels", "Live DJ"],
  },
  {
    id: "dance-2",
    categoryId: "dance",
    title: "Bharatanatyam Basics",
    description:
      "An introductory session into classical Bharatanatyam with a certified guru.",
    fullDescription:
      "Vidya Shankar guides you through foundational adavus (steps), mudras (hand gestures), and facial expressions. Comfortable dance practice attire recommended.",
    ticketTiers: [
      {
        id: "d2-reg",
        name: "Standard Slot",
        price: 200,
        totalSeats: 40,
        bookedSeats: 22,
        heldSeats: 0,
      },
    ],
    location: "Nrithyasalai, Jayanagar, Bengaluru",
    hostedBy: "Vidya Shankar, Classical Dance Guru",
    duration: "2 hours",
    date: "Aug 23, 2026 · 9:00 AM",
    ageCategory: "10+",
    image: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=700",
    images: [
      "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=700",
      "https://images.unsplash.com/photo-1516475429186-3002799317b4?w=700",
      "https://images.unsplash.com/photo-1537365586614-4551069f1021?w=700",
    ],
    price: "₹200",
    tags: ["Classical", "Indian Art", "Beginners"],
  },
  {
    id: "food-1",
    categoryId: "food",
    title: "Street Bites India",
    description:
      "Curated food stalls from 15 cities, live cooking demos, and a national food quiz.",
    fullDescription:
      "Embark on a culinary road trip across India. 15 curated stalls: Kolkata kati rolls, Mumbai pav bhaji, Chennai idli podi, and more.",
    ticketTiers: [
      {
        id: "f1-eb",
        name: "Early Bird Entry",
        price: 99,
        totalSeats: 100,
        bookedSeats: 80,
        heldSeats: 0,
      },
      {
        id: "f1-reg",
        name: "General Admission",
        price: 199,
        totalSeats: 200,
        bookedSeats: 132,
        heldSeats: 0,
      },
    ],
    location: "Palace Grounds, Bengaluru",
    hostedBy: "FoodieCollective India",
    duration: "6 hours",
    date: "Aug 15, 2026 · 12:00 PM",
    ageCategory: "All Ages",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=700",
    images: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=700",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=700",
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=700",
    ],
    price: "From ₹99",
    tags: ["Street Food", "Family Friendly", "Cultural"],
  },
  {
    id: "food-2",
    categoryId: "food",
    title: "Ramen & Beyond",
    description:
      "Japanese noodle culture: four tasting flights, broth-making workshop, and sake pairing.",
    fullDescription:
      "Chef Akira Tanaka brings Tokyo to your bowl. Discover regional ramen styles and discover perfect sake pairings.",
    ticketTiers: [
      {
        id: "f2-eb",
        name: "Early Bird Foodie",
        price: 800,
        totalSeats: 20,
        bookedSeats: 15,
        heldSeats: 0,
      },
      {
        id: "f2-reg",
        name: "General Table",
        price: 1200,
        totalSeats: 40,
        bookedSeats: 18,
        heldSeats: 0,
      },
    ],
    location: "Umami House, MG Road, Bengaluru",
    hostedBy: "Chef Akira Tanaka",
    duration: "3 hours",
    date: "Aug 22, 2026 · 6:30 PM",
    ageCategory: "12+",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=700",
    images: [
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=700",
      "https://images.unsplash.com/photo-1514516322520-5a420806ad4b?w=700",
      "https://images.unsplash.com/photo-1552611052-33e04de081de?w=700",
    ],
    price: "From ₹800",
    tags: ["Japanese", "Fine Dining", "Workshop"],
  },
  {
    id: "mudpot-1",
    categoryId: "mudpot",
    title: "Earth & Hands",
    description:
      "Traditional Terracotta art with village artisans from Karnataka. Lunch included.",
    fullDescription:
      "A rare chance to learn traditional Terracotta craftsmanship directly from Channapatna village artisans at Janapada Loka.",
    ticketTiers: [
      {
        id: "m1-reg",
        name: "All-Inclusive Pass",
        price: 450,
        totalSeats: 25,
        bookedSeats: 19,
        heldSeats: 0,
      },
    ],
    location: "Janapada Loka, Ramanagara, Karnataka",
    hostedBy: "Kaavya Arts Trust",
    duration: "5 hours",
    date: "Aug 16, 2026 · 9:00 AM",
    ageCategory: "8+",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=700",
    images: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=700",
      "https://images.unsplash.com/photo-1593150501174-d88aa1b7bb67?w=700",
      "https://images.unsplash.com/photo-1490312278390-ab64016b5873?w=700",
    ],
    price: "₹450",
    tags: ["Heritage Craft", "Village Artisans", "Lunch Included"],
  },
  {
    id: "mudpot-2",
    categoryId: "mudpot",
    title: "Clay Chronicles",
    description:
      "Free-form clay sculpting combined with storytelling of Indus Valley pottery traditions.",
    fullDescription:
      "Dr. Anand Rao blends a history lecture with hands-on clay sculpting. Discover ancient traditions.",
    ticketTiers: [
      {
        id: "m2-eb",
        name: "Early Bird",
        price: 250,
        totalSeats: 10,
        bookedSeats: 8,
        heldSeats: 0,
      },
      {
        id: "m2-reg",
        name: "Regular Admission",
        price: 400,
        totalSeats: 20,
        bookedSeats: 6,
        heldSeats: 0,
      },
    ],
    location: "Heritage Studio, Basavanagudi, Bengaluru",
    hostedBy: "Dr. Anand Rao, Archaeologist & Potter",
    duration: "3.5 hours",
    date: "Aug 30, 2026 · 10:30 AM",
    ageCategory: "14+",
    image: "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=700",
    images: [
      "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=700",
      "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1?w=700",
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=700",
    ],
    price: "From ₹250",
    tags: ["History", "Clay Art", "Storytelling"],
  },
  {
    id: "tech-1",
    categoryId: "tech",
    title: "AI Builders Collective",
    description:
      "Hands-on LLM fine-tuning, open-stage project demos, and structured speed networking.",
    fullDescription:
      "Practical LLM fine-tuning on consumer GPUs, RAG pipeline architecture, and AI safety fundamentals.",
    ticketTiers: [
      {
        id: "t1-eb",
        name: "Early Dev Pass",
        price: 500,
        totalSeats: 40,
        bookedSeats: 30,
        heldSeats: 0,
      },
      {
        id: "t1-reg",
        name: "Builder Pass",
        price: 999,
        totalSeats: 80,
        bookedSeats: 58,
        heldSeats: 0,
      },
    ],
    location: "NASSCOM Hub, Whitefield, Bengaluru",
    hostedBy: "AIforIndia Community",
    duration: "5 hours",
    date: "Aug 8, 2026 · 10:00 AM",
    ageCategory: "18+",
    image: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=700",
    images: [
      "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=700",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=700",
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=700",
    ],
    price: "From ₹500",
    tags: ["AI/ML", "Networking", "Demos", "Meals Included"],
  },
  {
    id: "tech-2",
    categoryId: "tech",
    title: "Open Source Sunday",
    description:
      "Contribute to OSS projects guided by core maintainers. Everyone ships real commits.",
    fullDescription:
      "Pair with open-source project maintainers to make real commits — from documentation to feature PRs.",
    ticketTiers: [
      {
        id: "t2-eb",
        name: "Early Bird",
        price: 100,
        totalSeats: 30,
        bookedSeats: 20,
        heldSeats: 0,
      },
      {
        id: "t2-reg",
        name: "Contributor Pass",
        price: 200,
        totalSeats: 50,
        bookedSeats: 21,
        heldSeats: 0,
      },
    ],
    location: "HasGeek Space, Domlur, Bengaluru",
    hostedBy: "FOSS United",
    duration: "4 hours",
    date: "Aug 24, 2026 · 11:00 AM",
    ageCategory: "16+",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=700",
    images: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=700",
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=700",
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=700",
    ],
    price: "From ₹100",
    tags: ["Open Source", "Coding", "Community"],
  },
  {
    id: "strangers-1",
    categoryId: "strangers",
    title: "100 Strangers Café",
    description:
      "Structured conversation games designed to forge genuine human connections.",
    fullDescription:
      "Arrive alone, leave with friends. The evening features 3 rounds of curated conversation prompts.",
    ticketTiers: [
      {
        id: "s1-eb",
        name: "Early Bird Solo",
        price: 200,
        totalSeats: 40,
        bookedSeats: 30,
        heldSeats: 0,
      },
      {
        id: "s1-reg",
        name: "Solo Explorer",
        price: 350,
        totalSeats: 60,
        bookedSeats: 37,
        heldSeats: 0,
      },
    ],
    location: "Indiranagar, Bengaluru",
    hostedBy: "Hello Stranger Network",
    duration: "2.5 hours",
    date: "Aug 7, 2026 · 6:00 PM",
    ageCategory: "18+",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=700",
    images: [
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=700",
      "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=700",
      "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=700",
    ],
    price: "From ₹200",
    tags: ["Social", "Games", "Community"],
  },
  {
    id: "strangers-2",
    categoryId: "strangers",
    title: "First Hello",
    description:
      "An ice-breaker evening for introverts — quiet games, story cards, and a shared dinner.",
    fullDescription:
      "Small tables of 6, facilitated by empathetic hosts, using story card prompts. Shared dinner included.",
    ticketTiers: [
      {
        id: "s2-eb",
        name: "Early Bird",
        price: 400,
        totalSeats: 20,
        bookedSeats: 15,
        heldSeats: 0,
      },
      {
        id: "s2-reg",
        name: "Introvert Class",
        price: 600,
        totalSeats: 30,
        bookedSeats: 13,
        heldSeats: 0,
      },
    ],
    location: "Sadashivanagar, Bengaluru",
    hostedBy: "Introvert Circle India",
    duration: "3 hours",
    date: "Aug 21, 2026 · 7:00 PM",
    ageCategory: "21+",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=700",
    images: [
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=700",
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=700",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=700",
    ],
    price: "From ₹400",
    tags: ["Introverts", "Dinner Included", "Small Group"],
  },
  {
    id: "cinema-1",
    categoryId: "cinema",
    title: "Midnight Mystery Movie",
    description:
      "A secret cult classic screening at an old heritage theater with vintage atmosphere.",
    fullDescription:
      "We don't reveal the movie until the lights go down. Enjoy a curated experience.",
    ticketTiers: [
      {
        id: "c1-eb",
        name: "Early Bird Balcony",
        price: 150,
        totalSeats: 20,
        bookedSeats: 15,
        heldSeats: 0,
      },
      {
        id: "c1-reg",
        name: "Stall Admission",
        price: 250,
        totalSeats: 30,
        bookedSeats: 13,
        heldSeats: 0,
      },
    ],
    location: "Everest Theater, Fraser Town, Bengaluru",
    hostedBy: "Film Club Bengaluru",
    duration: "3 hours",
    date: "Aug 21, 2026 · 11:30 PM",
    ageCategory: "18+",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=700",
    images: [
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=700",
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=700",
      "https://images.unsplash.com/photo-1517604401827-944e6ed4d388?w=700",
    ],
    price: "From ₹150",
    tags: ["Cinema", "Mystery", "Retro Theater"],
  },
  {
    id: "comedy-1",
    categoryId: "comedy",
    title: "Comedy Circus Gurgaon | A Standup Come...",
    description:
      "The funniest upcoming comics trying out their fresh new material.",
    fullDescription:
      "10 comics, 5 minutes each. Hosted by a surprise headliner from the national circuit.",
    // MATCHING YOUR SCREENSHOT MODEL
    ticketTiers: [
      {
        id: "eb",
        name: "Early Bird",
        price: 199,
        totalSeats: 20,
        bookedSeats: 10,
        heldSeats: 0,
      },
      {
        id: "reg",
        name: "Regular Ticket",
        price: 299,
        totalSeats: 25,
        bookedSeats: 25,
        heldSeats: 0,
      },
      {
        id: "cb",
        name: "Couple or buddies",
        price: 499,
        totalSeats: 5,
        bookedSeats: 0,
        heldSeats: 0,
      },
    ],
    location: "That Comedy Club, Koramangala, Bengaluru",
    hostedBy: "Comedy Central India",
    duration: "2 hours",
    date: "Aug 12, 2026 · 8:00 PM",
    ageCategory: "18+",
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=700",
    images: [
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=700",
      "https://images.unsplash.com/photo-1585699324551-f6c309eedee5?w=700",
      "https://images.unsplash.com/photo-1543584730-184755104031?w=700",
    ],
    price: "From ₹199",
    tags: ["Standup", "Nightlife", "New Material"],
  },
];

export const INITIAL_FEEDBACKS: Feedback[] = [
  {
    id: "fb1",
    eventId: "art-1",
    username: "Ashikaseelan",
    rating: 5,
    comment:
      "Priya is an absolutely inspiring teacher. I painted my first real watercolor and I'm completely hooked!",
    timestamp: "July 15, 2026",
  },
  {
    id: "fb2",
    eventId: "strangers-1",
    username: "Kaviya",
    rating: 5,
    comment:
      "I came alone and left with four new friends I genuinely want to keep in touch with. A magic evening.",
    timestamp: "July 8, 2026",
  },
  {
    id: "fb3",
    eventId: "tech-1",
    username: "Kalaivani",
    rating: 4,
    comment:
      "The LLM fine-tuning workshop was dense in the best way. Walked out with a working LoRA adapter!",
    timestamp: "July 20, 2026",
  },
  {
    id: "fb4",
    eventId: "food-1",
    username: "Aishwariya",
    rating: 5,
    comment:
      "Street Bites India is unmissable every year. The Kolkata egg roll stall was absolute perfection.",
    timestamp: "July 14, 2026",
  },
  {
    id: "fb5",
    eventId: "dance-1",
    username: "Arun",
    rating: 5,
    comment:
      "I stepped on every partner's toes and laughed through all of it. Perfect night out in the city.",
    timestamp: "July 10, 2026",
  },
  {
    id: "fb6",
    eventId: "mudpot-1",
    username: "Arjun N.",
    rating: 5,
    comment:
      "The village artisans at Janapada Loka are the kindest teachers. My terracotta pot has pride of place on my shelf.",
    timestamp: "July 18, 2026",
  },
];
